#!/usr/bin/env ruby

require 'router_crypt'

puts "Paste hash, including leading characters, below."
print "> "
pass_hash = gets.chomp

if pass_hash.start_with? '$9$'
  plain_text_pass = RouterCrypt::JunOS.decrypt pass_hash
else
  plain_text_pass = RouterCrypt::IOS.decrypt pass_hash
end


puts "\n\nOriginal hash: #{pass_hash}"
puts "Plain-Text   : #{plain_text_pass}"
